// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1ruysvY6Ch1EZ3oRAyr3zyBp2aLK8EE',
    appId: '1:11842777591:web:1aa660ad3e89dd2a217ef2',
    messagingSenderId: '11842777591',
    projectId: 'notosuru-1fda5',
    authDomain: 'notosuru-1fda5.firebaseapp.com',
    storageBucket: 'notosuru-1fda5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5AX8gwDJpB0oJQsXFo7Y8eXn8s-vBeoE',
    appId: '1:11842777591:android:5157c0b42063cbae217ef2',
    messagingSenderId: '11842777591',
    projectId: 'notosuru-1fda5',
    storageBucket: 'notosuru-1fda5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu6B_6zk_J01N9de-gLNR7PIiiDHcdDRI',
    appId: '1:11842777591:ios:50f50e08293eb59c217ef2',
    messagingSenderId: '11842777591',
    projectId: 'notosuru-1fda5',
    storageBucket: 'notosuru-1fda5.appspot.com',
    iosBundleId: 'com.example.notosuru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu6B_6zk_J01N9de-gLNR7PIiiDHcdDRI',
    appId: '1:11842777591:ios:027fb6f1726ec60f217ef2',
    messagingSenderId: '11842777591',
    projectId: 'notosuru-1fda5',
    storageBucket: 'notosuru-1fda5.appspot.com',
    iosBundleId: 'com.example.notosuru.RunnerTests',
  );
}
